/*
 * generated by Xtext 2.9.1
 */
package fmautorepair.ui;

import com.google.inject.Injector;
import fmautorepair.kconfig.ui.internal.KconfigActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KconfigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KconfigActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KconfigActivator.getInstance().getInjector(KconfigActivator.FMAUTOREPAIR_KCONFIG);
	}
	
}
