/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig.impl;

import fmautorepair.kconfig.KconfigPackage;
import fmautorepair.kconfig.NeqLiteral;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Neq Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NeqLiteralImpl extends KconfigExprImpl implements NeqLiteral
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NeqLiteralImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return KconfigPackage.Literals.NEQ_LITERAL;
  }

} //NeqLiteralImpl
