/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fmautorepair.kconfig.KconfigPackage#getAndLiteral()
 * @model
 * @generated
 */
public interface AndLiteral extends KconfigExpr
{
} // AndLiteral
