/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Choice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fmautorepair.kconfig.Choice#getChoice <em>Choice</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Choice#getConfigs <em>Configs</em>}</li>
 * </ul>
 *
 * @see fmautorepair.kconfig.KconfigPackage#getChoice()
 * @model
 * @generated
 */
public interface Choice extends EObject
{
  /**
   * Returns the value of the '<em><b>Choice</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Choice</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choice</em>' attribute.
   * @see #setChoice(String)
   * @see fmautorepair.kconfig.KconfigPackage#getChoice_Choice()
   * @model
   * @generated
   */
  String getChoice();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Choice#getChoice <em>Choice</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Choice</em>' attribute.
   * @see #getChoice()
   * @generated
   */
  void setChoice(String value);

  /**
   * Returns the value of the '<em><b>Configs</b></em>' containment reference list.
   * The list contents are of type {@link fmautorepair.kconfig.Config}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Configs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configs</em>' containment reference list.
   * @see fmautorepair.kconfig.KconfigPackage#getChoice_Configs()
   * @model containment="true"
   * @generated
   */
  EList<Config> getConfigs();

} // Choice
