/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Config Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fmautorepair.kconfig.ConfigLiteral#getConf <em>Conf</em>}</li>
 *   <li>{@link fmautorepair.kconfig.ConfigLiteral#getString <em>String</em>}</li>
 * </ul>
 *
 * @see fmautorepair.kconfig.KconfigPackage#getConfigLiteral()
 * @model
 * @generated
 */
public interface ConfigLiteral extends EObject
{
  /**
   * Returns the value of the '<em><b>Conf</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conf</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conf</em>' reference.
   * @see #setConf(Config)
   * @see fmautorepair.kconfig.KconfigPackage#getConfigLiteral_Conf()
   * @model
   * @generated
   */
  Config getConf();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.ConfigLiteral#getConf <em>Conf</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conf</em>' reference.
   * @see #getConf()
   * @generated
   */
  void setConf(Config value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(String)
   * @see fmautorepair.kconfig.KconfigPackage#getConfigLiteral_String()
   * @model
   * @generated
   */
  String getString();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.ConfigLiteral#getString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #getString()
   * @generated
   */
  void setString(String value);

} // ConfigLiteral
