/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Default</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fmautorepair.kconfig.Default#getValue <em>Value</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Default#getTrival <em>Trival</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Default#getHex <em>Hex</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Default#getInt <em>Int</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Default#getKconfigExpr <em>Kconfig Expr</em>}</li>
 * </ul>
 *
 * @see fmautorepair.kconfig.KconfigPackage#getDefault()
 * @model
 * @generated
 */
public interface Default extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(KconfigExpr)
   * @see fmautorepair.kconfig.KconfigPackage#getDefault_Value()
   * @model containment="true"
   * @generated
   */
  KconfigExpr getValue();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Default#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(KconfigExpr value);

  /**
   * Returns the value of the '<em><b>Trival</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Trival</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trival</em>' attribute.
   * @see #setTrival(String)
   * @see fmautorepair.kconfig.KconfigPackage#getDefault_Trival()
   * @model
   * @generated
   */
  String getTrival();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Default#getTrival <em>Trival</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trival</em>' attribute.
   * @see #getTrival()
   * @generated
   */
  void setTrival(String value);

  /**
   * Returns the value of the '<em><b>Hex</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hex</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hex</em>' attribute.
   * @see #setHex(String)
   * @see fmautorepair.kconfig.KconfigPackage#getDefault_Hex()
   * @model
   * @generated
   */
  String getHex();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Default#getHex <em>Hex</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hex</em>' attribute.
   * @see #getHex()
   * @generated
   */
  void setHex(String value);

  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(int)
   * @see fmautorepair.kconfig.KconfigPackage#getDefault_Int()
   * @model
   * @generated
   */
  int getInt();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Default#getInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #getInt()
   * @generated
   */
  void setInt(int value);

  /**
   * Returns the value of the '<em><b>Kconfig Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kconfig Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kconfig Expr</em>' containment reference.
   * @see #setKconfigExpr(KconfigExpr)
   * @see fmautorepair.kconfig.KconfigPackage#getDefault_KconfigExpr()
   * @model containment="true"
   * @generated
   */
  KconfigExpr getKconfigExpr();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Default#getKconfigExpr <em>Kconfig Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kconfig Expr</em>' containment reference.
   * @see #getKconfigExpr()
   * @generated
   */
  void setKconfigExpr(KconfigExpr value);

} // Default
