/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Dependency</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fmautorepair.kconfig.Dependency#getDeps <em>Deps</em>}</li>
 * </ul>
 *
 * @see fmautorepair.kconfig.KconfigPackage#getDependency()
 * @model
 * @generated
 */
public interface Dependency extends EObject
{
  /**
   * Returns the value of the '<em><b>Deps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Deps</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Deps</em>' containment reference.
   * @see #setDeps(KconfigExpr)
   * @see fmautorepair.kconfig.KconfigPackage#getDependency_Deps()
   * @model containment="true"
   * @generated
   */
  KconfigExpr getDeps();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Dependency#getDeps <em>Deps</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Deps</em>' containment reference.
   * @see #getDeps()
   * @generated
   */
  void setDeps(KconfigExpr value);

} // Dependency
