/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fmautorepair.kconfig.KconfigPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends KconfigExpr
{
} // Expr
