/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fmautorepair.kconfig.KconfigFactory
 * @model kind="package"
 * @generated
 */
public interface KconfigPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "kconfig";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Kconfig.fmautorepair";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "kconfig";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  KconfigPackage eINSTANCE = fmautorepair.kconfig.impl.KconfigPackageImpl.init();

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.ModelImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Choices</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CHOICES = 0;

  /**
   * The feature id for the '<em><b>Sources</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__SOURCES = 1;

  /**
   * The feature id for the '<em><b>Configs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONFIGS = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.ChoiceImpl <em>Choice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.ChoiceImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getChoice()
   * @generated
   */
  int CHOICE = 1;

  /**
   * The feature id for the '<em><b>Choice</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__CHOICE = 0;

  /**
   * The feature id for the '<em><b>Configs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE__CONFIGS = 1;

  /**
   * The number of structural features of the '<em>Choice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOICE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.ImportImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.ConfigImpl <em>Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.ConfigImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getConfig()
   * @generated
   */
  int CONFIG = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__TYPE = 1;

  /**
   * The feature id for the '<em><b>Prompts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__PROMPTS = 2;

  /**
   * The feature id for the '<em><b>Ranges</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__RANGES = 3;

  /**
   * The feature id for the '<em><b>Dependencies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__DEPENDENCIES = 4;

  /**
   * The feature id for the '<em><b>Selects</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__SELECTS = 5;

  /**
   * The feature id for the '<em><b>Defaults</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG__DEFAULTS = 6;

  /**
   * The number of structural features of the '<em>Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.TypeImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getType()
   * @generated
   */
  int TYPE = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Tprompt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__TPROMPT = 1;

  /**
   * The feature id for the '<em><b>Kconfig Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__KCONFIG_EXPR = 2;

  /**
   * The feature id for the '<em><b>Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__DEF = 3;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.DependencyImpl <em>Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.DependencyImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getDependency()
   * @generated
   */
  int DEPENDENCY = 5;

  /**
   * The feature id for the '<em><b>Deps</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__DEPS = 0;

  /**
   * The number of structural features of the '<em>Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.SelectImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 6;

  /**
   * The feature id for the '<em><b>Select</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__SELECT = 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__EXPR = 1;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.DefaultImpl <em>Default</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.DefaultImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getDefault()
   * @generated
   */
  int DEFAULT = 7;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT__VALUE = 0;

  /**
   * The feature id for the '<em><b>Trival</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT__TRIVAL = 1;

  /**
   * The feature id for the '<em><b>Hex</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT__HEX = 2;

  /**
   * The feature id for the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT__INT = 3;

  /**
   * The feature id for the '<em><b>Kconfig Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT__KCONFIG_EXPR = 4;

  /**
   * The number of structural features of the '<em>Default</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFAULT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.PromptImpl <em>Prompt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.PromptImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getPrompt()
   * @generated
   */
  int PROMPT = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__VALUE = 0;

  /**
   * The feature id for the '<em><b>Kconfig Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT__KCONFIG_EXPR = 1;

  /**
   * The number of structural features of the '<em>Prompt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROMPT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.RangeImpl <em>Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.RangeImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getRange()
   * @generated
   */
  int RANGE = 9;

  /**
   * The feature id for the '<em><b>Ifrom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__IFROM = 0;

  /**
   * The feature id for the '<em><b>Iconfrom</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__ICONFROM = 1;

  /**
   * The feature id for the '<em><b>Ito</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__ITO = 2;

  /**
   * The feature id for the '<em><b>Iconfto</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__ICONFTO = 3;

  /**
   * The feature id for the '<em><b>Hfrom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__HFROM = 4;

  /**
   * The feature id for the '<em><b>Hto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__HTO = 5;

  /**
   * The feature id for the '<em><b>Kconfig Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__KCONFIG_EXPR = 6;

  /**
   * The number of structural features of the '<em>Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.KconfigExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.KconfigExprImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getKconfigExpr()
   * @generated
   */
  int KCONFIG_EXPR = 10;

  /**
   * The feature id for the '<em><b>Confslit</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KCONFIG_EXPR__CONFSLIT = 0;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KCONFIG_EXPR__LEFT = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KCONFIG_EXPR__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KCONFIG_EXPR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.ConfigLiteralImpl <em>Config Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.ConfigLiteralImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getConfigLiteral()
   * @generated
   */
  int CONFIG_LITERAL = 11;

  /**
   * The feature id for the '<em><b>Conf</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LITERAL__CONF = 0;

  /**
   * The feature id for the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LITERAL__STRING = 1;

  /**
   * The number of structural features of the '<em>Config Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIG_LITERAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.ExprImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 12;

  /**
   * The feature id for the '<em><b>Confslit</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__CONFSLIT = KCONFIG_EXPR__CONFSLIT;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__LEFT = KCONFIG_EXPR__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__RIGHT = KCONFIG_EXPR__RIGHT;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = KCONFIG_EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.NeqLiteralImpl <em>Neq Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.NeqLiteralImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getNeqLiteral()
   * @generated
   */
  int NEQ_LITERAL = 13;

  /**
   * The feature id for the '<em><b>Confslit</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ_LITERAL__CONFSLIT = KCONFIG_EXPR__CONFSLIT;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ_LITERAL__LEFT = KCONFIG_EXPR__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ_LITERAL__RIGHT = KCONFIG_EXPR__RIGHT;

  /**
   * The number of structural features of the '<em>Neq Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEQ_LITERAL_FEATURE_COUNT = KCONFIG_EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.AndLiteralImpl <em>And Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.AndLiteralImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getAndLiteral()
   * @generated
   */
  int AND_LITERAL = 14;

  /**
   * The feature id for the '<em><b>Confslit</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_LITERAL__CONFSLIT = KCONFIG_EXPR__CONFSLIT;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_LITERAL__LEFT = KCONFIG_EXPR__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_LITERAL__RIGHT = KCONFIG_EXPR__RIGHT;

  /**
   * The number of structural features of the '<em>And Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_LITERAL_FEATURE_COUNT = KCONFIG_EXPR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fmautorepair.kconfig.impl.OrLiteralImpl <em>Or Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fmautorepair.kconfig.impl.OrLiteralImpl
   * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getOrLiteral()
   * @generated
   */
  int OR_LITERAL = 15;

  /**
   * The feature id for the '<em><b>Confslit</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_LITERAL__CONFSLIT = KCONFIG_EXPR__CONFSLIT;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_LITERAL__LEFT = KCONFIG_EXPR__LEFT;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_LITERAL__RIGHT = KCONFIG_EXPR__RIGHT;

  /**
   * The number of structural features of the '<em>Or Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_LITERAL_FEATURE_COUNT = KCONFIG_EXPR_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fmautorepair.kconfig.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.Model#getChoices <em>Choices</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Choices</em>'.
   * @see fmautorepair.kconfig.Model#getChoices()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Choices();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.Model#getSources <em>Sources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sources</em>'.
   * @see fmautorepair.kconfig.Model#getSources()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Sources();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.Model#getConfigs <em>Configs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Configs</em>'.
   * @see fmautorepair.kconfig.Model#getConfigs()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Configs();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Choice <em>Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choice</em>'.
   * @see fmautorepair.kconfig.Choice
   * @generated
   */
  EClass getChoice();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Choice#getChoice <em>Choice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Choice</em>'.
   * @see fmautorepair.kconfig.Choice#getChoice()
   * @see #getChoice()
   * @generated
   */
  EAttribute getChoice_Choice();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.Choice#getConfigs <em>Configs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Configs</em>'.
   * @see fmautorepair.kconfig.Choice#getConfigs()
   * @see #getChoice()
   * @generated
   */
  EReference getChoice_Configs();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see fmautorepair.kconfig.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute list '{@link fmautorepair.kconfig.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Imported Namespace</em>'.
   * @see fmautorepair.kconfig.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Config <em>Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Config</em>'.
   * @see fmautorepair.kconfig.Config
   * @generated
   */
  EClass getConfig();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Config#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fmautorepair.kconfig.Config#getName()
   * @see #getConfig()
   * @generated
   */
  EAttribute getConfig_Name();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.Config#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see fmautorepair.kconfig.Config#getType()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_Type();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.Config#getPrompts <em>Prompts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Prompts</em>'.
   * @see fmautorepair.kconfig.Config#getPrompts()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_Prompts();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.Config#getRanges <em>Ranges</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ranges</em>'.
   * @see fmautorepair.kconfig.Config#getRanges()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_Ranges();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.Config#getDependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dependencies</em>'.
   * @see fmautorepair.kconfig.Config#getDependencies()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_Dependencies();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.Config#getSelects <em>Selects</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Selects</em>'.
   * @see fmautorepair.kconfig.Config#getSelects()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_Selects();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.Config#getDefaults <em>Defaults</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Defaults</em>'.
   * @see fmautorepair.kconfig.Config#getDefaults()
   * @see #getConfig()
   * @generated
   */
  EReference getConfig_Defaults();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see fmautorepair.kconfig.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Type#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see fmautorepair.kconfig.Type#getType()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Type();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Type#getTprompt <em>Tprompt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Tprompt</em>'.
   * @see fmautorepair.kconfig.Type#getTprompt()
   * @see #getType()
   * @generated
   */
  EAttribute getType_Tprompt();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.Type#getKconfigExpr <em>Kconfig Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Kconfig Expr</em>'.
   * @see fmautorepair.kconfig.Type#getKconfigExpr()
   * @see #getType()
   * @generated
   */
  EReference getType_KconfigExpr();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.Type#getDef <em>Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Def</em>'.
   * @see fmautorepair.kconfig.Type#getDef()
   * @see #getType()
   * @generated
   */
  EReference getType_Def();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Dependency <em>Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependency</em>'.
   * @see fmautorepair.kconfig.Dependency
   * @generated
   */
  EClass getDependency();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.Dependency#getDeps <em>Deps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Deps</em>'.
   * @see fmautorepair.kconfig.Dependency#getDeps()
   * @see #getDependency()
   * @generated
   */
  EReference getDependency_Deps();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see fmautorepair.kconfig.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the reference '{@link fmautorepair.kconfig.Select#getSelect <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Select</em>'.
   * @see fmautorepair.kconfig.Select#getSelect()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_Select();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.Select#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see fmautorepair.kconfig.Select#getExpr()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_Expr();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Default <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Default</em>'.
   * @see fmautorepair.kconfig.Default
   * @generated
   */
  EClass getDefault();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.Default#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see fmautorepair.kconfig.Default#getValue()
   * @see #getDefault()
   * @generated
   */
  EReference getDefault_Value();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Default#getTrival <em>Trival</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trival</em>'.
   * @see fmautorepair.kconfig.Default#getTrival()
   * @see #getDefault()
   * @generated
   */
  EAttribute getDefault_Trival();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Default#getHex <em>Hex</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hex</em>'.
   * @see fmautorepair.kconfig.Default#getHex()
   * @see #getDefault()
   * @generated
   */
  EAttribute getDefault_Hex();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Default#getInt <em>Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int</em>'.
   * @see fmautorepair.kconfig.Default#getInt()
   * @see #getDefault()
   * @generated
   */
  EAttribute getDefault_Int();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.Default#getKconfigExpr <em>Kconfig Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Kconfig Expr</em>'.
   * @see fmautorepair.kconfig.Default#getKconfigExpr()
   * @see #getDefault()
   * @generated
   */
  EReference getDefault_KconfigExpr();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Prompt <em>Prompt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prompt</em>'.
   * @see fmautorepair.kconfig.Prompt
   * @generated
   */
  EClass getPrompt();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Prompt#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fmautorepair.kconfig.Prompt#getValue()
   * @see #getPrompt()
   * @generated
   */
  EAttribute getPrompt_Value();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.Prompt#getKconfigExpr <em>Kconfig Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Kconfig Expr</em>'.
   * @see fmautorepair.kconfig.Prompt#getKconfigExpr()
   * @see #getPrompt()
   * @generated
   */
  EReference getPrompt_KconfigExpr();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range</em>'.
   * @see fmautorepair.kconfig.Range
   * @generated
   */
  EClass getRange();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Range#getIfrom <em>Ifrom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ifrom</em>'.
   * @see fmautorepair.kconfig.Range#getIfrom()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Ifrom();

  /**
   * Returns the meta object for the reference '{@link fmautorepair.kconfig.Range#getIconfrom <em>Iconfrom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Iconfrom</em>'.
   * @see fmautorepair.kconfig.Range#getIconfrom()
   * @see #getRange()
   * @generated
   */
  EReference getRange_Iconfrom();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Range#getIto <em>Ito</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ito</em>'.
   * @see fmautorepair.kconfig.Range#getIto()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Ito();

  /**
   * Returns the meta object for the reference '{@link fmautorepair.kconfig.Range#getIconfto <em>Iconfto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Iconfto</em>'.
   * @see fmautorepair.kconfig.Range#getIconfto()
   * @see #getRange()
   * @generated
   */
  EReference getRange_Iconfto();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Range#getHfrom <em>Hfrom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hfrom</em>'.
   * @see fmautorepair.kconfig.Range#getHfrom()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Hfrom();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.Range#getHto <em>Hto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Hto</em>'.
   * @see fmautorepair.kconfig.Range#getHto()
   * @see #getRange()
   * @generated
   */
  EAttribute getRange_Hto();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.Range#getKconfigExpr <em>Kconfig Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Kconfig Expr</em>'.
   * @see fmautorepair.kconfig.Range#getKconfigExpr()
   * @see #getRange()
   * @generated
   */
  EReference getRange_KconfigExpr();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.KconfigExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see fmautorepair.kconfig.KconfigExpr
   * @generated
   */
  EClass getKconfigExpr();

  /**
   * Returns the meta object for the containment reference list '{@link fmautorepair.kconfig.KconfigExpr#getConfslit <em>Confslit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Confslit</em>'.
   * @see fmautorepair.kconfig.KconfigExpr#getConfslit()
   * @see #getKconfigExpr()
   * @generated
   */
  EReference getKconfigExpr_Confslit();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.KconfigExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fmautorepair.kconfig.KconfigExpr#getLeft()
   * @see #getKconfigExpr()
   * @generated
   */
  EReference getKconfigExpr_Left();

  /**
   * Returns the meta object for the containment reference '{@link fmautorepair.kconfig.KconfigExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fmautorepair.kconfig.KconfigExpr#getRight()
   * @see #getKconfigExpr()
   * @generated
   */
  EReference getKconfigExpr_Right();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.ConfigLiteral <em>Config Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Config Literal</em>'.
   * @see fmautorepair.kconfig.ConfigLiteral
   * @generated
   */
  EClass getConfigLiteral();

  /**
   * Returns the meta object for the reference '{@link fmautorepair.kconfig.ConfigLiteral#getConf <em>Conf</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Conf</em>'.
   * @see fmautorepair.kconfig.ConfigLiteral#getConf()
   * @see #getConfigLiteral()
   * @generated
   */
  EReference getConfigLiteral_Conf();

  /**
   * Returns the meta object for the attribute '{@link fmautorepair.kconfig.ConfigLiteral#getString <em>String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>String</em>'.
   * @see fmautorepair.kconfig.ConfigLiteral#getString()
   * @see #getConfigLiteral()
   * @generated
   */
  EAttribute getConfigLiteral_String();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see fmautorepair.kconfig.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.NeqLiteral <em>Neq Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Neq Literal</em>'.
   * @see fmautorepair.kconfig.NeqLiteral
   * @generated
   */
  EClass getNeqLiteral();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.AndLiteral <em>And Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Literal</em>'.
   * @see fmautorepair.kconfig.AndLiteral
   * @generated
   */
  EClass getAndLiteral();

  /**
   * Returns the meta object for class '{@link fmautorepair.kconfig.OrLiteral <em>Or Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Literal</em>'.
   * @see fmautorepair.kconfig.OrLiteral
   * @generated
   */
  EClass getOrLiteral();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  KconfigFactory getKconfigFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.ModelImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Choices</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CHOICES = eINSTANCE.getModel_Choices();

    /**
     * The meta object literal for the '<em><b>Sources</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__SOURCES = eINSTANCE.getModel_Sources();

    /**
     * The meta object literal for the '<em><b>Configs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__CONFIGS = eINSTANCE.getModel_Configs();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.ChoiceImpl <em>Choice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.ChoiceImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getChoice()
     * @generated
     */
    EClass CHOICE = eINSTANCE.getChoice();

    /**
     * The meta object literal for the '<em><b>Choice</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHOICE__CHOICE = eINSTANCE.getChoice_Choice();

    /**
     * The meta object literal for the '<em><b>Configs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOICE__CONFIGS = eINSTANCE.getChoice_Configs();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.ImportImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.ConfigImpl <em>Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.ConfigImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getConfig()
     * @generated
     */
    EClass CONFIG = eINSTANCE.getConfig();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG__NAME = eINSTANCE.getConfig_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__TYPE = eINSTANCE.getConfig_Type();

    /**
     * The meta object literal for the '<em><b>Prompts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__PROMPTS = eINSTANCE.getConfig_Prompts();

    /**
     * The meta object literal for the '<em><b>Ranges</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__RANGES = eINSTANCE.getConfig_Ranges();

    /**
     * The meta object literal for the '<em><b>Dependencies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__DEPENDENCIES = eINSTANCE.getConfig_Dependencies();

    /**
     * The meta object literal for the '<em><b>Selects</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__SELECTS = eINSTANCE.getConfig_Selects();

    /**
     * The meta object literal for the '<em><b>Defaults</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG__DEFAULTS = eINSTANCE.getConfig_Defaults();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.TypeImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__TYPE = eINSTANCE.getType_Type();

    /**
     * The meta object literal for the '<em><b>Tprompt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__TPROMPT = eINSTANCE.getType_Tprompt();

    /**
     * The meta object literal for the '<em><b>Kconfig Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__KCONFIG_EXPR = eINSTANCE.getType_KconfigExpr();

    /**
     * The meta object literal for the '<em><b>Def</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TYPE__DEF = eINSTANCE.getType_Def();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.DependencyImpl <em>Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.DependencyImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getDependency()
     * @generated
     */
    EClass DEPENDENCY = eINSTANCE.getDependency();

    /**
     * The meta object literal for the '<em><b>Deps</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEPENDENCY__DEPS = eINSTANCE.getDependency_Deps();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.SelectImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Select</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__SELECT = eINSTANCE.getSelect_Select();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__EXPR = eINSTANCE.getSelect_Expr();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.DefaultImpl <em>Default</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.DefaultImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getDefault()
     * @generated
     */
    EClass DEFAULT = eINSTANCE.getDefault();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFAULT__VALUE = eINSTANCE.getDefault_Value();

    /**
     * The meta object literal for the '<em><b>Trival</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFAULT__TRIVAL = eINSTANCE.getDefault_Trival();

    /**
     * The meta object literal for the '<em><b>Hex</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFAULT__HEX = eINSTANCE.getDefault_Hex();

    /**
     * The meta object literal for the '<em><b>Int</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEFAULT__INT = eINSTANCE.getDefault_Int();

    /**
     * The meta object literal for the '<em><b>Kconfig Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFAULT__KCONFIG_EXPR = eINSTANCE.getDefault_KconfigExpr();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.PromptImpl <em>Prompt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.PromptImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getPrompt()
     * @generated
     */
    EClass PROMPT = eINSTANCE.getPrompt();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROMPT__VALUE = eINSTANCE.getPrompt_Value();

    /**
     * The meta object literal for the '<em><b>Kconfig Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROMPT__KCONFIG_EXPR = eINSTANCE.getPrompt_KconfigExpr();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.RangeImpl <em>Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.RangeImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getRange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getRange();

    /**
     * The meta object literal for the '<em><b>Ifrom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__IFROM = eINSTANCE.getRange_Ifrom();

    /**
     * The meta object literal for the '<em><b>Iconfrom</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RANGE__ICONFROM = eINSTANCE.getRange_Iconfrom();

    /**
     * The meta object literal for the '<em><b>Ito</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__ITO = eINSTANCE.getRange_Ito();

    /**
     * The meta object literal for the '<em><b>Iconfto</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RANGE__ICONFTO = eINSTANCE.getRange_Iconfto();

    /**
     * The meta object literal for the '<em><b>Hfrom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__HFROM = eINSTANCE.getRange_Hfrom();

    /**
     * The meta object literal for the '<em><b>Hto</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGE__HTO = eINSTANCE.getRange_Hto();

    /**
     * The meta object literal for the '<em><b>Kconfig Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RANGE__KCONFIG_EXPR = eINSTANCE.getRange_KconfigExpr();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.KconfigExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.KconfigExprImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getKconfigExpr()
     * @generated
     */
    EClass KCONFIG_EXPR = eINSTANCE.getKconfigExpr();

    /**
     * The meta object literal for the '<em><b>Confslit</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KCONFIG_EXPR__CONFSLIT = eINSTANCE.getKconfigExpr_Confslit();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KCONFIG_EXPR__LEFT = eINSTANCE.getKconfigExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KCONFIG_EXPR__RIGHT = eINSTANCE.getKconfigExpr_Right();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.ConfigLiteralImpl <em>Config Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.ConfigLiteralImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getConfigLiteral()
     * @generated
     */
    EClass CONFIG_LITERAL = eINSTANCE.getConfigLiteral();

    /**
     * The meta object literal for the '<em><b>Conf</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIG_LITERAL__CONF = eINSTANCE.getConfigLiteral_Conf();

    /**
     * The meta object literal for the '<em><b>String</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIG_LITERAL__STRING = eINSTANCE.getConfigLiteral_String();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.ExprImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.NeqLiteralImpl <em>Neq Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.NeqLiteralImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getNeqLiteral()
     * @generated
     */
    EClass NEQ_LITERAL = eINSTANCE.getNeqLiteral();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.AndLiteralImpl <em>And Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.AndLiteralImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getAndLiteral()
     * @generated
     */
    EClass AND_LITERAL = eINSTANCE.getAndLiteral();

    /**
     * The meta object literal for the '{@link fmautorepair.kconfig.impl.OrLiteralImpl <em>Or Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fmautorepair.kconfig.impl.OrLiteralImpl
     * @see fmautorepair.kconfig.impl.KconfigPackageImpl#getOrLiteral()
     * @generated
     */
    EClass OR_LITERAL = eINSTANCE.getOrLiteral();

  }

} //KconfigPackage
