/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fmautorepair.kconfig.Model#getChoices <em>Choices</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Model#getSources <em>Sources</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Model#getConfigs <em>Configs</em>}</li>
 * </ul>
 *
 * @see fmautorepair.kconfig.KconfigPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Choices</b></em>' containment reference list.
   * The list contents are of type {@link fmautorepair.kconfig.Choice}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Choices</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choices</em>' containment reference list.
   * @see fmautorepair.kconfig.KconfigPackage#getModel_Choices()
   * @model containment="true"
   * @generated
   */
  EList<Choice> getChoices();

  /**
   * Returns the value of the '<em><b>Sources</b></em>' containment reference list.
   * The list contents are of type {@link fmautorepair.kconfig.Import}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sources</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sources</em>' containment reference list.
   * @see fmautorepair.kconfig.KconfigPackage#getModel_Sources()
   * @model containment="true"
   * @generated
   */
  EList<Import> getSources();

  /**
   * Returns the value of the '<em><b>Configs</b></em>' containment reference list.
   * The list contents are of type {@link fmautorepair.kconfig.Config}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Configs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configs</em>' containment reference list.
   * @see fmautorepair.kconfig.KconfigPackage#getModel_Configs()
   * @model containment="true"
   * @generated
   */
  EList<Config> getConfigs();

} // Model
