/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Prompt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fmautorepair.kconfig.Prompt#getValue <em>Value</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Prompt#getKconfigExpr <em>Kconfig Expr</em>}</li>
 * </ul>
 *
 * @see fmautorepair.kconfig.KconfigPackage#getPrompt()
 * @model
 * @generated
 */
public interface Prompt extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see fmautorepair.kconfig.KconfigPackage#getPrompt_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Prompt#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

  /**
   * Returns the value of the '<em><b>Kconfig Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kconfig Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kconfig Expr</em>' containment reference.
   * @see #setKconfigExpr(KconfigExpr)
   * @see fmautorepair.kconfig.KconfigPackage#getPrompt_KconfigExpr()
   * @model containment="true"
   * @generated
   */
  KconfigExpr getKconfigExpr();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Prompt#getKconfigExpr <em>Kconfig Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kconfig Expr</em>' containment reference.
   * @see #getKconfigExpr()
   * @generated
   */
  void setKconfigExpr(KconfigExpr value);

} // Prompt
