/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fmautorepair.kconfig.Range#getIfrom <em>Ifrom</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Range#getIconfrom <em>Iconfrom</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Range#getIto <em>Ito</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Range#getIconfto <em>Iconfto</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Range#getHfrom <em>Hfrom</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Range#getHto <em>Hto</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Range#getKconfigExpr <em>Kconfig Expr</em>}</li>
 * </ul>
 *
 * @see fmautorepair.kconfig.KconfigPackage#getRange()
 * @model
 * @generated
 */
public interface Range extends EObject
{
  /**
   * Returns the value of the '<em><b>Ifrom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ifrom</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ifrom</em>' attribute.
   * @see #setIfrom(String)
   * @see fmautorepair.kconfig.KconfigPackage#getRange_Ifrom()
   * @model
   * @generated
   */
  String getIfrom();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Range#getIfrom <em>Ifrom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ifrom</em>' attribute.
   * @see #getIfrom()
   * @generated
   */
  void setIfrom(String value);

  /**
   * Returns the value of the '<em><b>Iconfrom</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Iconfrom</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iconfrom</em>' reference.
   * @see #setIconfrom(Config)
   * @see fmautorepair.kconfig.KconfigPackage#getRange_Iconfrom()
   * @model
   * @generated
   */
  Config getIconfrom();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Range#getIconfrom <em>Iconfrom</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iconfrom</em>' reference.
   * @see #getIconfrom()
   * @generated
   */
  void setIconfrom(Config value);

  /**
   * Returns the value of the '<em><b>Ito</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ito</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ito</em>' attribute.
   * @see #setIto(String)
   * @see fmautorepair.kconfig.KconfigPackage#getRange_Ito()
   * @model
   * @generated
   */
  String getIto();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Range#getIto <em>Ito</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ito</em>' attribute.
   * @see #getIto()
   * @generated
   */
  void setIto(String value);

  /**
   * Returns the value of the '<em><b>Iconfto</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Iconfto</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Iconfto</em>' reference.
   * @see #setIconfto(Config)
   * @see fmautorepair.kconfig.KconfigPackage#getRange_Iconfto()
   * @model
   * @generated
   */
  Config getIconfto();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Range#getIconfto <em>Iconfto</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Iconfto</em>' reference.
   * @see #getIconfto()
   * @generated
   */
  void setIconfto(Config value);

  /**
   * Returns the value of the '<em><b>Hfrom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hfrom</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hfrom</em>' attribute.
   * @see #setHfrom(String)
   * @see fmautorepair.kconfig.KconfigPackage#getRange_Hfrom()
   * @model
   * @generated
   */
  String getHfrom();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Range#getHfrom <em>Hfrom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hfrom</em>' attribute.
   * @see #getHfrom()
   * @generated
   */
  void setHfrom(String value);

  /**
   * Returns the value of the '<em><b>Hto</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hto</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hto</em>' attribute.
   * @see #setHto(String)
   * @see fmautorepair.kconfig.KconfigPackage#getRange_Hto()
   * @model
   * @generated
   */
  String getHto();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Range#getHto <em>Hto</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Hto</em>' attribute.
   * @see #getHto()
   * @generated
   */
  void setHto(String value);

  /**
   * Returns the value of the '<em><b>Kconfig Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kconfig Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kconfig Expr</em>' containment reference.
   * @see #setKconfigExpr(KconfigExpr)
   * @see fmautorepair.kconfig.KconfigPackage#getRange_KconfigExpr()
   * @model containment="true"
   * @generated
   */
  KconfigExpr getKconfigExpr();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Range#getKconfigExpr <em>Kconfig Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kconfig Expr</em>' containment reference.
   * @see #getKconfigExpr()
   * @generated
   */
  void setKconfigExpr(KconfigExpr value);

} // Range
