/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fmautorepair.kconfig.Select#getSelect <em>Select</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Select#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see fmautorepair.kconfig.KconfigPackage#getSelect()
 * @model
 * @generated
 */
public interface Select extends EObject
{
  /**
   * Returns the value of the '<em><b>Select</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Select</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Select</em>' reference.
   * @see #setSelect(Config)
   * @see fmautorepair.kconfig.KconfigPackage#getSelect_Select()
   * @model
   * @generated
   */
  Config getSelect();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Select#getSelect <em>Select</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Select</em>' reference.
   * @see #getSelect()
   * @generated
   */
  void setSelect(Config value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(KconfigExpr)
   * @see fmautorepair.kconfig.KconfigPackage#getSelect_Expr()
   * @model containment="true"
   * @generated
   */
  KconfigExpr getExpr();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Select#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(KconfigExpr value);

} // Select
