/**
 * generated by Xtext 2.9.1
 */
package fmautorepair.kconfig;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fmautorepair.kconfig.Type#getType <em>Type</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Type#getTprompt <em>Tprompt</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Type#getKconfigExpr <em>Kconfig Expr</em>}</li>
 *   <li>{@link fmautorepair.kconfig.Type#getDef <em>Def</em>}</li>
 * </ul>
 *
 * @see fmautorepair.kconfig.KconfigPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see fmautorepair.kconfig.KconfigPackage#getType_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Type#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Tprompt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tprompt</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tprompt</em>' attribute.
   * @see #setTprompt(String)
   * @see fmautorepair.kconfig.KconfigPackage#getType_Tprompt()
   * @model
   * @generated
   */
  String getTprompt();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Type#getTprompt <em>Tprompt</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tprompt</em>' attribute.
   * @see #getTprompt()
   * @generated
   */
  void setTprompt(String value);

  /**
   * Returns the value of the '<em><b>Kconfig Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Kconfig Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Kconfig Expr</em>' containment reference.
   * @see #setKconfigExpr(KconfigExpr)
   * @see fmautorepair.kconfig.KconfigPackage#getType_KconfigExpr()
   * @model containment="true"
   * @generated
   */
  KconfigExpr getKconfigExpr();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Type#getKconfigExpr <em>Kconfig Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Kconfig Expr</em>' containment reference.
   * @see #getKconfigExpr()
   * @generated
   */
  void setKconfigExpr(KconfigExpr value);

  /**
   * Returns the value of the '<em><b>Def</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Def</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Def</em>' containment reference.
   * @see #setDef(KconfigExpr)
   * @see fmautorepair.kconfig.KconfigPackage#getType_Def()
   * @model containment="true"
   * @generated
   */
  KconfigExpr getDef();

  /**
   * Sets the value of the '{@link fmautorepair.kconfig.Type#getDef <em>Def</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Def</em>' containment reference.
   * @see #getDef()
   * @generated
   */
  void setDef(KconfigExpr value);

} // Type
