/*
 * generated by Xtext 2.9.1
 */
package fmautorepair.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKconfigScopeProvider extends DelegatingScopeProvider {
}
