/*
 * generated by Xtext 2.9.1
 */
package fmautorepair.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KconfigAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fmautorepair/parser/antlr/internal/InternalKconfig.tokens");
	}
}
