/*
 * generated by Xtext 2.9.1
 */
package fmautorepair.parser.antlr;

import com.google.inject.Inject;
import fmautorepair.parser.antlr.internal.InternalKconfigParser;
import fmautorepair.services.KconfigGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KconfigParser extends AbstractAntlrParser {

	@Inject
	private KconfigGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKconfigParser createParser(XtextTokenStream stream) {
		return new InternalKconfigParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public KconfigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KconfigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
