/*
 * generated by Xtext 2.9.1
 */
package fmautorepair


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class KconfigStandaloneSetup extends KconfigStandaloneSetupGenerated {

	def static void doSetup() {
		new KconfigStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
